// Ecosystem configuration - auto-generated by create-template
//
// Services enabled based on evolution-run-config.jsonc:
//   - Core: gRPC variation, render socket server
//   - Reference features
//   - UMAP projection
//   - Quality musicality evaluation
//
// Staggered cron restarts (every 2 hours) for stateless services to prevent ECONNRESET storms.

// Environment variables for portability:
//   KROMOSYNTH_ROOT   - Base path for kromosynth repos (default: /Users/bjornpjo/Developer/apps/synth.is)
//   KROMOSYNTH_NODE   - Path to node interpreter (default: uses nvm)
//   KROMOSYNTH_PYTHON - Path to python interpreter (default: ${ROOT}/kromosynth-evaluate/.venv/bin/python3)
//   KROMOSYNTH_VENDOR - Path to vendor directory (default: /Users/bjornpjo/Developer/vendor)

const ROOT = process.env.KROMOSYNTH_ROOT || '/Users/bjornpjo/Developer/apps/synth.is';
const VENDOR = process.env.KROMOSYNTH_VENDOR || '/Users/bjornpjo/Developer/vendor';
const NODE = process.env.KROMOSYNTH_NODE || '/Users/bjornpjo/.nvm/versions/node/v18.20.3/bin/node';
const PYTHON = process.env.KROMOSYNTH_PYTHON || `${ROOT}/kromosynth-evaluate/.venv/bin/python3`;

export default {
  apps: [
    {
      name: "kromosynth-gRPC-variation",
      instances: 3,
      exec_mode: "cluster",
      max_memory_restart: "1500M",
      increment_var: "PORT",
      interpreter: NODE,
      cwd: `${ROOT}/kromosynth-cli`,
      script: "gRPC/genomeVariationWS.js",
      args: `--max-old-space-size=1024 --processTitle kromosynth-gRPC-variation --modelUrl file://${VENDOR}/tfjs-model_yamnet_tfjs_1/model.json`,
      cron_restart: "10 */2 * * *",
      env: {
        PORT: 50051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    },
    {
      name: "kromosynth-render-socket-server",
      instances: 3,
      exec_mode: "cluster",
      max_memory_restart: "1500M",
      increment_var: "PORT",
      interpreter: NODE,
      script: `${ROOT}/kromosynth-render/render-socket/socket-server-floating-points.js`,
      args: "--max-old-space-size=1024 --processTitle kromosynth-render-socket-server",
      cron_restart: "20 */2 * * *",
      env: {
        PORT: 60051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    },
    {
      name: "kromosynth-evaluation-socket-server_features",
      instances: 3,
      exec_mode: "fork",
      max_memory_restart: "2G",
      increment_var: "PORT",
      interpreter: PYTHON,
      cwd: `${ROOT}/kromosynth-evaluate`,
      script: "evaluation/unsupervised/features.py",
      args: "--host 127.0.0.1",
      cron_restart: "30 */2 * * *",
      env: {
        PORT: 61051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    },
    {
      name: "kromosynth-evaluation-socket-server_quality_ref_features",
      instances: 3,
      exec_mode: "fork",
      max_memory_restart: "2G",
      increment_var: "PORT",
      interpreter: PYTHON,
      cwd: `${ROOT}/kromosynth-evaluate`,
      script: "evaluation/unsupervised/quality_ref_features.py",
      args: "--host 127.0.0.1",
      cron_restart: "40 */2 * * *",
      env: {
        PORT: 62051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    },
    {
      name: "kromosynth-evaluation-socket-server_projection_pca_quantised",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "4G",
      increment_var: "PORT",
      interpreter: PYTHON,
      cwd: `${ROOT}/kromosynth-evaluate`,
      script: "evaluation/unsupervised/projection_quantised.py",
      args: `--host 127.0.0.1 --dimensions 2 --dimension-cells 100`,
      env: {
        PORT: 33051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    },
    {
      name: "kromosynth-quality-musicality-service",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "2G",
      increment_var: "PORT",
      interpreter: PYTHON,
      cwd: `${ROOT}/kromosynth-evaluate`,
      script: "evaluation/unsupervised/quality_musicality.py",
      args: `--host 127.0.0.1 --port 32051 --sample-rate 16000 --process-title quality_musicality`,
      cron_restart: "50 */2 * * *",
      env: {
        PORT: 32051,
        TF_FORCE_GPU_ALLOW_GROWTH: true
      }
    }
  ]
};
